title: Spatial Data Science for Drought Dynamics and Risk Assessment
description: Characterising spatio-temporal variability, mapping risk and predicting drought severity.

theme: minima

header_pages:
  - about.md
  - applications.md
  - results.md
  - publications.md
  - outreach.md
  - team.md
