title: Spatial Data Science for Drought Risk Assessment
description: Research project on the use of spatial and spatio-temporal data science methods for drought risk assessment.

theme: minima

header_pages:
  - about.md
  - team.md
  - methods.md
  - results.md
  - publications.md
  - outreach.md
